language: java
jdk:
  - openjdk8

jobs:
  include:
    - name: test
      if: tag IS blank
      script: 
        - mvn test -B
    - name: deploy
      if: tag IS present
      script: 
        - mvn package -B
        - ls
        - ls target
      env:
        global:
          secure: rBjrOMe3KdztZ9FuURu7cwCnnQuEt9i42/gQb7wgB0B2Sznaji+uf72VjqG7z9xK3TpeBklTzByYxqrkbHJDhBNeKoWrI6wTJYLiFCpFYpfrQ0bCxQfFSj6xL+1yTkRUlGJ4gl9LzqLjoNkMjYuAk/pc7b7TK61VCfgLUvkbzmm3F1XJMKWK1QAQzJt6pI/vNlNVcByfxUgsoHrXEOf5puIUGLEBOXYQzZw6zmTM1E6hFDcUP1Na/pqLUdk/twMpBw1DHnRVhsvw1AIsbcSmIx/OIwZzFWRPGC03x9o+z/LQrQhlN9doJzRonRdC6Z4CP9RgpEGliIkye+er7aSQINHnR2JZHoQVWVdOsqcpK6QoDfNGnGXHm44FpLd9r1p3vGGgUo9DjKcuq8IfK7emjEfDnUNcLnwv6feVkWRitLBzv8EC/3U2moWN0GtoEMZK/xd9tW4+eoUCgGF8SKQwPPiUeXDj9U8pWoj2O5Ai2qji3YmGG/BQA0QYfhz+7kcoafziJ3y1hgU3T/OJdQSvuUJXIImmsTjyHwfDEoTcsY5ppzsoBUDrrDtGiTle/c3y73pmcckKClczGde1wuLvW90fA2l1hPPBnsEaXIopX6RDYxauIMLklOjGLc3LYcMacUz3avOybcg8eSLp7m4knxHZ5bquZDIpNjq+8+FJQJQ=
      deploy:
        provider: releases
        api_key:
          secure: eRDyj/N2/cZYaGlp/SqnTEe6XMXrSACDYmZ8uMrZlr+n/zzB/QYNFRAoKoT61D8JXiv+Up7jMEcO8AbIuLUV9drxZSalM3UGreiCD95Cml8ylrI789kuTz87SpqYOUtwxza6DcHWGOQz9pih7WFLIlCJn+TNqj+GwzlbE04YJwTHJymxE5TlVB5D/xaJV0b/053eLcioZIv8qHksza2Los2xm1Og3mwFYU4TkiMJlY2s163RvnuPkUX/zSv7OcsC7yNo4jaiAtHTdeCyki30v5AzjSrmKfzyDGTmjjyNSF6Xve08Q3JS+6xFXuAq+U+rrLEM9TSuZPQhejXuVy30IKyh0vfUwEOpPacul5eV/GTgBx7AwyWQm4HqI6Sh6o4ayzarC5R2LXn3aI/wVL0TemZ/LaPzGrgiZoIwuKZIPDQw8/SHqyiw4oQzvsTSUW4HZOwg7xxa8MpdxwB3ltVic1J9a8U9lpyrfbHAo49N+ymZYwwCbESvz1pLS2FbwlzYcEySbt8JwN5yyfKabfe/4gkhOET98DgyF7eetS8LJKTEReRcUwhs+K9cC2RWYF6YE7GwahBredZqS649hWTYXMHj44Niu1B3VPPisMf0TCOOS3WDIEuXff067YT8/v+LSRdDzpshfBJ9eH2lXLDV3MxzWrIxiT2h14F16od9hhE=
        file_glob: true
        file: ./target/*.jar
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - bash scripts/increase_minor.sh
        - bash scripts/push_pom.sh

cache:
  directories:
  - "$HOME/.m2"

after-success:
  - bash <(curl -s https://codecov.io/bash)


