language: java
jdk:
  - openjdk8

jobs:
  include:
    - name: test
      if: tag IS blank
      script: 
        - mvn test -B

    - name: deploy
      if: tag IS present
      before_script:
        - cp ./.travis/settings.xml $HOME/.m2
      script: 
        - mvn deploy -B
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ./target/toast-*.jar
        skip_cleanup: true
        on:
          tags: true

cache:
  directories:
  - "$HOME/.m2"

after-success:
  - bash <(curl -s https://codecov.io/bash)


