language: java
jdk:
  - openjdk8

jobs:
  include:
    - name: test
      if: tag IS blank
      script: 
        - mvn test -B
    - name: deploy
      if: tag IS present
      env:
        secure: "sLJ5YnPSvvdGcXyWj5cHuBnVjaVrFnqZMYw+uQs56JG9Qc2qsFwg6FGcwkslsBVHGqdJTzvZIKR8Ct+AIb0UR94v3RXiJuyOQ4gCq46oBqWhU8W3Fq8UAbIfKhILYRGN6XA4VdPsZklzcu7vxsUA+TT90JcobfSvyK7KEJCLeGysy7vuRgZnTF7Ew7vjC7IEd3PTRMBmwDSVRyYtP8frpuU+0VvbrcbBVh0cG0Uzoj1tHjaRx14OA9QIuQbqscMkJry2UQy/tGu66l6BJvFMeE/AXLp1395xs5PCYNjA6NPL0cQ/p0jSpuWUfG+T8tz47uwkIsAeVf72RRMxc4nTMAYKBYl+YXzwbJtp7kqsnMd1THBt/YWYtDuR/OS166fkF90Lfq+dtRxQe5erDuTe7dcmola6DoKBoGxBA5W0PztQtZJvEy5jh15oL6rV+6l+ARXsMdntkH6CujoQq12afub2PjFGyoJvvWgumNFPYLmhAj1j4iccbZAJxWXKJAQC94zVbAVrfnqYKrm8e439NSQ8xcUAXyVCNpn5jUSs0eI7J22lOlZKeUDqT2d2smBGNLVRYfJJHLZNyBx4lcJu3psPkAIkiw3481jEh3V8sh4yL67jFDLx0+ui4l0XeR6nfk5MrZI4/B5/H9mVzUaytAexT84Ik5rxu3/z8yzAj0s="
      script: 
        - mvn package -B
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ./target/*.jar
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - bash scripts/increase_minor.sh
        - bash scripts/push_pom.sh

cache:
  directories:
  - "$HOME/.m2"

after-success:
  - bash <(curl -s https://codecov.io/bash)


