language: java
jdk:
  - openjdk8

jobs:
  include:
    - name: test
      if: tag IS blank
      script: 
        - mvn test -B
    - name: deploy
      if: tag IS present
      script: 
        - mvn package -B
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ./target/*.jar
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - bash scripts/increase_minor.sh
        - bash scripts/push_pom.sh

cache:
  directories:
  - "$HOME/.m2"

after-success:
  - bash <(curl -s https://codecov.io/bash)


