language: java
jdk:
  - openjdk8

jobs:
  include:
    - name: test
      if: tag IS blank
      script: 
        - mvn test -B

    - name: deploy
      if: tag IS present
      before_script:
        - cp ./.travis/settings.xml $HOME/.m2
        - ls $HOME/.m2
        - cat $HOME/.m2/settings.xml
      script: 
        - mvn deploy -B
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ./target/jelly-*.jar
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - bash scripts/setup_git.sh
        - bash scripts/prepare_snapshot.sh

cache:
  directories:
  - "$HOME/.m2"

after-success:
  - bash <(curl -s https://codecov.io/bash)


